name: 💡 Feature  Request
description: Suggest an idea for this project.
title: "[Feature Request]: "
labels: ["Feature Request"]
body:
  - type: textarea
    attributes:
      label: Issue Description
      description: Please include a clear and concise description of the feature request.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Include as much of the information how the feature works as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: The expected output or behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: The actual output or behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Analysis
      description: If you have an idea how to achieve this new feature, let us know that here. Please include any pointers to code, relevant changes, or related issues you know of.
  - type: textarea
    attributes:
      label: Versions & Configurations
      description: |
        In a Visual Studio developer command prompt, run `msbuild -version` and paste the output here.
        If applicable, include the version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc).
        Post any other relevant configuration settings here: OS, architecture, etc.